### ISSUE TITLE
Hello, there was a problem while training with your dataset. Can you answer it? Thank you very much.

### ISSUE THREAD

**Issue by enick123** [JianghaiSCU/R2RNet#19]
![1682872830809](https://user-images.githubusercontent.com/104207422/235365197-cb61dbda-d8fa-4983-b5f8-98074c2e24fa.png)

**Comment by xiwang-online** [comment]
I have the same problem, have you solved it?

**Comment by Mac-jie** [comment]
I meet the same error. After i debugging the code, i can say there must be some problems in this offical code. (I am so confused that why the author concatenate these two images)
`cat_image = np.concatenate([result_1, result_2], axis=2)`

I will list reasons for my confusion in aspects of codes fellow:
First, the function psnr2() must get two images that both of them have the same dimensions.The function needs two images 'img1', 'img2'
`def psnr2(img1, img2):
    mse = np.mean((img1 / 255. - img2 / 255.) ** 2)
    if mse < 1.0e-10:
        return 100
    PIXEL_MAX = 1
    return 20 * math.log10(PIXEL_MAX / math.sqrt(mse))`
Second, the result_1 is R_low and result_2  is I_low_3(which is from `I_low_3 = torch.cat((I_low, I_low, I_low), dim=1)`), the shape of them is (720,960,3). The code fellow is that gets the input img1 'im_test', the shape of it must be (720,1920,3).
`                if train_phase == "Decom":
                    # read the methods in paper
                    self.forward(input_low_eval, input_low_eval)
                    result_1 = self.output_R_low
                    result_2 = self.output_I_low
                    input = np.squeeze(input_low_eval)
                    result_1 = np.squeeze(result_1)
                    result_2 = np.squeeze(result_2)
                    cat_image = np.concatenate([result_1, result_2], axis=2)`
Third, the shape of input img2 'eval_high_img' is  (720,960,3). 
 So, how can the train.py run successfully.

I think the learners who will run this project should change the code in model.py. I will figure out it, and then, I still have some questions:
First, Why I_low_3 is concatenated by the I_low, and then concatenated  again into cat_image with R_low?
Second, it seems that the psnr is calculated at the each step of train, I think it should be calculated at the end of training.

**Comment by enick123** [comment]
您好 请问您会说中文吗？我不知道您是否发错了邮件












武萍
***@***.***


---Original---
From: ***@***.***&gt;
Date: Wed, Nov 8, 2023 12:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JianghaiSCU/R2RNet] Hello, there was a problem while trainingwith your dataset. Can you answer it? Thank you very much. (Issue #19)




 
I meet the same error. After i debugging the code, i can say there must be some problems in this offical code. (I am so confused that why the author concatenate these two images)
 cat_image = np.concatenate([result_1, result_2], axis=2)
 
I will list reasons for my confusion in aspects of codes fellow:
 First, the function psnr2() must get two images that both of them have the same dimensions.The function needs two images 'img1', 'img2'
 def psnr2(img1, img2): mse = np.mean((img1 / 255. - img2 / 255.) ** 2) if mse < 1.0e-10: return 100 PIXEL_MAX = 1 return 20 * math.log10(PIXEL_MAX / math.sqrt(mse))
 Second, the result_1 is R_low and result_2  is I_low_3(which is from I_low_3 = torch.cat((I_low, I_low, I_low), dim=1)), the shape of them is (720,960,3). The code fellow is that gets the input img1 'im_test', the shape of it must be (720,1920,3).
                 if train_phase == "Decom": # read the methods in paper self.forward(input_low_eval, input_low_eval) result_1 = self.output_R_low result_2 = self.output_I_low input = np.squeeze(input_low_eval) result_1 = np.squeeze(result_1) result_2 = np.squeeze(result_2) cat_image = np.concatenate([result_1, result_2], axis=2)
 Third, the shape of input img2 'eval_high_img' is  (720,960,3).
 So, how can the train.py run successfully.
 
I think the learners who will run this project should change the code in model.py. I will figure out it, and then, I still have some questions:
 First, Why I_low_3 is concatenated by the I_low, and then concatenated  again into cat_image with R_low?
 Second, it seems that the psnr is calculated at the each step of train, I think it should be calculated at the end of training.

**Comment by Mac-jie** [comment]
你好，打扰了。我是研究低光照增强的研究生。

运行R2RNet代码时出现了报错，在训练完Decom之后进入evaluate部分，计算psnr中，输入的两张图片无法保持shape一致，输入的两张图片维度是 im_test (720,1920,3) eval_high_img (720,960,3)。

debug代码发现输入的 im_test 是由 DecomNet 分解的 R_low 和 三通道的 I_low （即I_low_3）拼接而成，如果拼接那么 im_test 的维度无法与 eval_high_img  相等，evaluate() 代码中没有对 eval_high_img   的维度进行相关的操作。

我主要有两个疑问，如果您能解答我将不胜感激。
1、cat_image = np.concatenate([result_1, result_2], axis=2) 这段代码的拼接操作是不是存在一些问题。
      如果是为了将分解的图片进行重构，从而计算psnr ，直接拼接是不是不合适。
      还是说还需要其他操作，比如将 eval_high_img 放入Decom中进行分解，然后按照同样的流程构成 (720,1920,3），然后计算psnr。
2、为什么每一个网络训练完都要进行一次psnr计算，不应该是全部训练完之后，拿到最终的增强结果再去进行计算吗？

________________________________

**Comment by enick123** [comment]
您好，这不是我的文章，我也是遇到了问题要对作者进行提问，不知道为什么会抄送到我这里。


武萍
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JianghaiSCU/R2RNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月8日(星期三) 中午1:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JianghaiSCU/R2RNet] Hello, there was a problem while training with your dataset. Can you answer it? Thank you very much. (Issue #19)





 你好，打扰了。我是研究低光照增强的研究生。 
 
 运行R2RNet代码时出现了报错，在训练完Decom之后进入evaluate部分，计算psnr中，输入的两张图片无法保持shape一致，输入的两张图片维度是 im_test (720,1920,3) eval_high_img (720,960,3)。 
 
 debug代码发现输入的 im_test 是由 DecomNet 分解的 R_low 和 三通道的 I_low （即I_low_3）拼接而成，如果拼接那么 im_test 的维度无法与 eval_high_img  相等，evaluate() 代码中没有对 eval_high_img   的维度进行相关的操作。 
 
 我主要有两个疑问，如果您能解答我将不胜感激。 
 1、cat_image = np.concatenate([result_1, result_2], axis=2) 这段代码的拼接操作是不是存在一些问题。 
       如果是为了将分解的图片进行重构，从而计算psnr ，直接拼接是不是不合适。 
       还是说还需要其他操作，比如将 eval_high_img 放入Decom中进行分解，然后按照同样的流程构成 (720,1920,3），然后计算psnr。 
 2、为什么每一个网络训练完都要进行一次psnr计算，不应该是全部训练完之后，拿到最终的增强结果再去进行计算吗？ 
 
 ________________________________

**Comment by Mac-jie** [comment]
这样的，好的，请问你有解决嘛，或许可以加个好友。

________________________________

**Comment by enick123** [comment]
没能解决，我换方向了。




武萍
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JianghaiSCU/R2RNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月8日(星期三) 下午2:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JianghaiSCU/R2RNet] Hello, there was a problem while training with your dataset. Can you answer it? Thank you very much. (Issue #19)





 这样的，好的，请问你有解决嘛，或许可以加个好友。 
 
 ________________________________

**Comment by Mac-jie** [comment]
I solve the error by add some code in model.py--R2RNet()--evaluate(). you can replace the function evaluate() directly, but i hope you can understand what the reason is and why I add these code.

`  def evaluate(self, epoch_num, eval_low_data_names, eval_high_data_names, vis_dir, train_phase):
        # TODO: I'm confused now that what is the purpose of evaluate() function?
        # The evaluate part, begin after one epoch training finished. So the model is done temporarily and have the static number
        print("Evaluating for phase %s / epoch %d..." % (train_phase, epoch_num))
        psnr = 0
        with torch.no_grad():# Otherwise the intermediate gradient would take up huge amount of CUDA memory
            for idx in range(len(eval_low_data_names)):
                eval_low_img = Image.open(eval_low_data_names[idx])
                eval_low_img = np.array(eval_low_img, dtype="float32") / 255.0
                eval_low_img = np.transpose(eval_low_img, [2, 0, 1])
                input_low_eval = np.expand_dims(eval_low_img, axis=0)

                # eval_high_img = Image.open(eval_high_data_names[idx])
                # eval_high_img = np.array(eval_high_img, dtype="float32")

                # TODO: Here is the code of sloving problem
                # ------------------------------------------------------------------------------ #

                eval_high_img = Image.open(eval_high_data_names[idx])
                eval_high_img = np.array(eval_high_img, dtype="float32") / 255.0
                eval_high_img = np.transpose(eval_high_img, [2, 0, 1])
                input_high_eval = np.expand_dims(eval_low_img, axis=0)


                # ------------------------------------------------------------------------------ #

                if train_phase == "Decom":
                    # TODO: this part have passed through all progress in the network, through the R2RNet
                    # read the methods in paper
                    # TODO: Why here input are both input_low_eval
                    # self.forward(input_low_eval, input_low_eval)

                    # TODO: __Here is the code of sloving problem
                    # ------------------------------------------------------------------------------ #
                    self.forward(input_low_eval, input_high_eval)
                    # ------------------------------------------------------------------------------ #
                    # TODO: What is the result_1 and result_2 represent?
                    result_1 = self.output_R_low
                    result_2 = self.output_I_low

                    # TODO: __Here is the code of sloving problem
                    # ------------------------------------------------------------------------------ #
                    result_3 = self.output_R_high
                    result_4 = self.output_I_high
                    # ------------------------------------------------------------------------------ #
                    input = np.squeeze(input_low_eval)
                    # TODO: How the np.squeeze() down the dims from 3 to 2
                    result_1 = np.squeeze(result_1)
                    result_2 = np.squeeze(result_2)

                    # TODO: __Here is the code of sloving problem
                    # ------------------------------------------------------------------------------ #
                    result_3 = np.squeeze(result_3)
                    result_4 = np.squeeze(result_4)
                    # ------------------------------------------------------------------------------ #

                    # TODO: Why does the author pedrform concatenate the two images?
                    cat_image = np.concatenate([result_1, result_2], axis=2)
                    # TODO: __Here is the code of sloving problem
                    # ------------------------------------------------------------------------------ #
                    cat_image_high = np.concatenate([result_3, result_4], axis=2)
                    # ------------------------------------------------------------------------------ #


                if train_phase == 'Denoise':
                    self.forward(input_low_eval, input_low_eval)
                    result_1 = self.output_R_denoise
                    input = np.squeeze(input_low_eval)
                    result_1 = result_1.numpy().squeeze(0)
                    cat_image = result_1
                if train_phase == "Relight":
                    self.forward(input_low_eval, input_low_eval)
                    result_4 = self.output_S
                    input = np.squeeze(input_low_eval)
                    result_4 = result_4.numpy().squeeze(0)
                    cat_image = result_4

                cat_image = np.transpose(cat_image, (1, 2, 0))
            # print(cat_image.shape)
                im = Image.fromarray(np.clip(cat_image * 255.0, 0, 255.0).astype('uint8'))
                im_test = np.array(im, dtype='float32')

                # TODO: __Here is the code of sloving problem
                # ------------------------------------------------------------------------------ #
                cat_image_high = np.transpose(cat_image_high, (1, 2, 0))
            # print(cat_image.shape)
                im_high = Image.fromarray(np.clip(cat_image_high * 255.0, 0, 255.0).astype('uint8'))
                im_test_high = np.array(im_high, dtype='float32')
                # ------------------------------------------------------------------------------ #

                # TODO: im_test (720,1920,3) eval_high_img (720,960,3)
                psnr += psnr2(im_test, im_test_high)

            print('psnr=', psnr / len(eval_low_data_names))
            writer.add_scalar('runs/psnr', psnr / len(eval_low_data_names), epoch_num)
`

After adding these code, i run the project successfully, The purpose of function evaluate() is to calculate the PSNR, but the error happen in `train_phase == "Decom"` ,  then, The author concatenate the decomposed result which through DecomNet into img1 and directly use eval_high_img as img2. I think img2 should use the the decomposed result through DecomNet, process just like the img1. 

Finally, The new evaluate() function will get the same shape for the input of psnr2().

**Comment by xiepip** [comment]
> I solve the error by add some code in model.py--R2RNet()--evaluate(). you can replace the function evaluate() directly, but i hope you can understand what the reason is and why I add these code.
> 
> ```
> def evaluate(self, epoch_num, eval_low_data_names, eval_high_data_names, vis_dir, train_phase):
> 
>         print("Evaluating for phase %s / epoch %d..." % (train_phase, epoch_num))
>         psnr = 0
>         with torch.no_grad():
>             for idx in range(len(eval_low_data_names)):
>                 eval_low_img = Image.open(eval_low_data_names[idx])
>                 eval_low_img = np.array(eval_low_img, dtype="float32") / 255.0
>                 eval_low_img = np.transpose(eval_low_img, [2, 0, 1])
>                 input_low_eval = np.expand_dims(eval_low_img, axis=0)
>                 eval_high_img = Image.open(eval_high_data_names[idx])
>                 eval_high_img = np.array(eval_high_img, dtype="float32") / 255.0
>                 eval_high_img = np.transpose(eval_high_img, [2, 0, 1])
>                 input_high_eval = np.expand_dims(eval_low_img, axis=0)
> 
>                 if train_phase == "Decom":
>                     self.forward(input_low_eval, input_high_eval)
>      
>                     result_1 = self.output_R_low
>                     result_2 = self.output_I_low
>                     result_3 = self.output_R_high
>                     result_4 = self.output_I_high
>                     input = np.squeeze(input_low_eval)
>                     result_1 = np.squeeze(result_1)
>                     result_2 = np.squeeze(result_2)
> 
>                     result_3 = np.squeeze(result_3)
>                     result_4 = np.squeeze(result_4)
> 
>                     cat_image = np.concatenate([result_1, result_2], axis=2)
>                     cat_image_high = np.concatenate([result_3, result_4], axis=2)
> 
> 
>                 if train_phase == 'Denoise':
>                     self.forward(input_low_eval, input_low_eval)
>                     result_1 = self.output_R_denoise
>                     input = np.squeeze(input_low_eval)
>                     result_1 = result_1.numpy().squeeze(0)
>                     cat_image = result_1
>                 if train_phase == "Relight":
>                     self.forward(input_low_eval, input_low_eval)
>                     result_4 = self.output_S
>                     input = np.squeeze(input_low_eval)
>                     result_4 = result_4.numpy().squeeze(0)
>                     cat_image = result_4
> 
>                 cat_image = np.transpose(cat_image, (1, 2, 0))
>             # print(cat_image.shape)
>                 im = Image.fromarray(np.clip(cat_image * 255.0, 0, 255.0).astype('uint8'))
>                 im_test = np.array(im, dtype='float32')
> 
>                 cat_image_high = np.transpose(cat_image_high, (1, 2, 0))
>             # print(cat_image.shape)
>                 im_high = Image.fromarray(np.clip(cat_image_high * 255.0, 0, 255.0).astype('uint8'))
>                 im_test_high = np.array(im_high, dtype='float32')
> 
>                 # TODO: im_test (720,1920,3) eval_high_img (720,960,3)
>                 psnr += psnr2(im_test, im_test_high)
> 
>             print('psnr=', psnr / len(eval_low_data_names))
>             writer.add_scalar('runs/psnr', psnr / len(eval_low_data_names), epoch_num)
> ```
> 
> After adding these code, i run the project successfully, The purpose of function evaluate() is to calculate the PSNR, but the error happen in `train_phase == "Decom"` , then, The author concatenate the decomposed result which through DecomNet into img1 and directly use eval_high_img as img2. I think img2 should use the the decomposed result through DecomNet, process just like the img1.
> 
> Finally, The new evaluate() function will get the same shape for the input of psnr2().
> 
> # ---------------------------------------------------------------------------------#
> update line 2023-11-10
> 
> # ---------------------------------------------------------------------------------#
> I found that replacing the function evaluate() directly will result in another error(So, don't follow the previous solution, adopt the new one):
> 
> ```
> Traceback (most recent call last):
>   File "/home/jie/PycharmProjects/Low_light/Datasets/LSWR/R2RNet-main/train.py", line 101, in <module>
>     train(model)
>   File "/home/jie/PycharmProjects/Low_light/Datasets/LSWR/R2RNet-main/train.py", line 74, in train
>     model.train(train_low_data_names,
>   File "/home/jie/PycharmProjects/Low_light/Datasets/LSWR/R2RNet-main/model.py", line 968, in train
>     self.evaluate(epoch + 1, eval_low_data_names, eval_high_data_names,
>   File "/home/jie/PycharmProjects/Low_light/Datasets/LSWR/R2RNet-main/model.py", line 791, in evaluate
>     cat_image_high = np.transpose(cat_image_high, (1, 2, 0))
> UnboundLocalError: local variable 'cat_image_high' referenced before assignment
> ```
> 
> it was in phase of Relight, I found the psnr is calculated every pahse(three phases totally), I think it's unnecessary, and finally I just put
> 
> ```
> cat_image = np.transpose(cat_image, (1, 2, 0))
>                 # print(cat_image.shape)
>                     im = Image.fromarray(np.clip(cat_image * 255.0, 0, 255.0).astype('uint8'))
>                     im_test = np.array(im, dtype='float32')
>                     psnr += psnr2(im_test, eval_high_img)
> ```
> 
> into
> 
> ```
>                 if train_phase == "Relight":
>                     self.forward(input_low_eval, input_low_eval)
>                     result_4 = self.output_S
>                     input = np.squeeze(input_low_eval)
>                     result_4 = result_4.numpy().squeeze(0)
>                     cat_image = result_4
> ```
> 
> Then, the project runs successfully. I have so many questions about the project, if you are study the R2RNet, I think we can have a communication with each other to help ourselves.

您好，我现在也在复现R2R，可以交流一下吗？您这里说的只在relight阶段计算psnr，最后运行跑通了吗？

**Comment by Mac-jie** [comment]
可以交流一下，你的研究方向也是低光照增强吗？
