### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'vgg16.we'

### ISSUE THREAD

**Issue by dangzhenmo** [JianghaiSCU/R2RNet#21]
I am a junior undergraduate student and I was attempting to run your code on Kaggle, but encountered the following error that left me quite puzzled.

Traceback (most recent call last):
  File "/kaggle/input/scu-model-3/R2RNet-main/predict.py", line 47, in <module>
    predict(model)
  File "/kaggle/input/scu-model-3/R2RNet-main/predict.py", line 31, in predict
    model.predict(test_low_data_names,
  File "/kaggle/input/scu-model-3/R2RNet-main/model.py", line 911, in predict
    load_model_status, _ = self.load(ckpt_dir)
  File "/kaggle/input/scu-model-3/R2RNet-main/model.py", line 755, in load
    global_step = int(load_ckpt[:-4])
ValueError: invalid literal for int() with base 10: 'vgg16.we'

Here is the directory structure on Kaggle that I have：
![image](https://github.com/JianghaiSCU/R2RNet/assets/155149675/c721cce1-ce1b-41e9-8057-c2b684761061)
I tried to change the file directory to relative paths, but it's still not working. I hope to get your help.Thank you very much!

**Comment by dangzhenmo** [comment]
I have resolved this issue on my own. To use this model for prediction, it is important to avoid two misconceptions. Firstly, do not follow the instructions in the readme.md to place vgg16.weight separately into folders like Decom, as this will result in errors. Additionally, you need to create another 'model' directory within R2RNet and place the vgg16.weight file inside it.
